version: '3.3'

services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blacklist_tracker
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5433:5432'
    image: postgres:16.1-alpine
    networks:
      - postgres

networks:
  postgres:

volumes:
  postgres: