openapi: 3.0.0
info:
  version: 1.0.0
  title: BlacklistTracker
servers:
  - url: "http://localhost:8080"
    description: "local testing"

paths:
  /blacklist:
    post:
      operationId: addBlacklistEntry
      summary: add entry in blacklist
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/blacklist_entry'
      responses:
        default:
          description: error occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '201':
          description: entry created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/empty'
  /blacklist/lua:
    get:
      summary: download lua
      operationId: downloadLua
      description: this API is for file download
      responses:
        default:
          description: error occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        200:
          description: Operation performed successfully.
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/binary'
components:
  schemas:
    empty:
      title: "Empty"
      description: "empty data transfer object"
      type: object
      readOnly: true
    error:
      title: "Error"
      description: "error message/reason"
      type: string
      readOnly: true
      nullable: false
      example: "error happened due to xyz"
    binary:
      type: string
      format: binary
    blacklist_entry:
      title: "BlacklistEntry"
      description: "Entry of the Blacklist"
      type: object
      required:
        - playerName
        - realm
        - reason
      properties:
        guid:
          title: "GUID"
          description: "GUID of the blacklisted Player"
          type: string
          nullable: false
          example: "XXX"
        playername:
          title: "Playername"
          description: "Name of the blacklisted Player"
          type: string
          nullable: false
          example: "Retailandy"
        realm:
          title: "Realm"
          description: "Realm of the blacklisted Player"
          type: string
          nullable: false
          example: "EU - Lone Wolf"
        faction:
          title: "Faction"
          description: "Faction of the blacklisted Player"
          type: string
          nullable: false
          enum: ["H", "A"]
          example: "H"
        reason:
          title: "Reason"
          description: "Reason for blacklisting"
          type: string
          nullable: false
          enum: ["ninjaloot", "scam", "unknown"]
          example: "ninjaloot"