spring:
  main.banner-mode: "off"
  profiles:
    active: postgres
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties.hibernate:
      format_sql: true
---
spring:
  config.activate.on-profile: postgres
  datasource:
    driverClassName: org.postgresql.Driver
